name: user_repository
description: manages the user domain
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  http: ^0.13.0
  json_annotation: ^4.4.0
  user_api:
    path: ../user_api

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  test: ^1.21.0
  coverage: ^1.0.3