name: ptk_inventory
description: Equipment Inventory At PTK NovSU
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  formz: ^0.4.1
  google_fonts: ^2.3.1
  flutter_services_binding: ^0.1.0
  flow_builder: ^0.0.4
  # позволит нам сохранять состояние приложения при его закрытии и повторном открытии
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  http: ^0.13.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  # позволяет нам легко подготовить наши блоки к тестированию, обрабатывать изменения состояния и проверять результаты последовательным образом.
  bloc_test: ^9.0.2
  json_serializable: ^6.0.0
  build_runner: ^2.1.10
  mocktail: ^0.2.0
  flutter_launcher_icons: "^0.9.0"
  hive_generator: ^1.1.2
  lint: ^1.8.2

flutter_icons:
  image_path: "images/4.0x/logo.png"
  android: true
  ios: true
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/1.5x/logo.png
    - images/2.0x/logo.png
    - images/3.0x/logo.png
    - images/4.0x/logo.png

  fonts:
   - family: PT Sans
     fonts:
       - asset: fonts/PTSans-Regular.ttf
       - asset: fonts/PTSans-Bold.ttf
         weight: 700
   - family: PT Sans Caption
     fonts:
       - asset: fonts/PTSansCaption-Regular.ttf
       - asset: fonts/PTSansCaption-Bold.ttf
         weight: 700
