name: equipment_repository
description: manages the equipment domain
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  equipment_api:
    path: ../equipment_api

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  mocktail: ^0.2.0
  test: ^1.16.4