name: equipment_api
description: A Dart API Client for Equipment-Inventory API
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
    http: ^0.13.0
    json_annotation: ^4.4.0
    user_api:
      path: ../user_api


dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.21.0
  mocktail: ^0.3.0
  mockito: ^5.1.0