name: inventory_api
description: A Dart API Client for Equipment-Inventory API
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.4.0
  equipment_api:
    path: ../equipment_api
    
dev_dependencies:
  json_serializable: ^6.0.0
  build_runner: ^2.0.0